version: '3'

services:
  postgres:
    restart: always
    image: postgres
    container_name: roadini_cdn_db
    environment:
      - POSTGRES_PASSWORD=cdnadmin
      - POSTGRES_DB=dbCDN
    networks:
      - roadiniserver_proxynet
    volumes:
        - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./backups/postgresql:/backupo

  api:
    container_name: cdnapi
    image: cdn
    working_dir: /app
    volumes:
      - ./CDNservice:/app
    links:
      - postgres
    command: mvn clean spring-boot:run
    depends_on:
      - postgres
    networks:
      - roadiniserver_proxynet

  recognition:
    build: ./ImageRecognition
    working_dir: /imageApp
    volumes:
      - ./ImageRecognition:/imageApp
    container_name: imageRecognition
    command: mvn clean spring-boot:run
    networks:
      - roadiniserver_proxynet

networks:
    roadiniserver_proxynet:
        external: true
