version: '3'

services:
  postgres:
    restart: always
    image: postgres
    container_name: roadini_cdn_db
    environment:
      - POSTGRES_PASSWORD=cdnadmin
      - POSTGRES_DB=dbCDN
    networks:
      - roadiniserver_proxynet
    volumes:
        - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        - ./backups/postgresql:/backupo

  apiv1:
    container_name: cdnapiv1
    image: cdnv1
    working_dir: /cdnv1app
    volumes:
      - ./CDNservice/v1:/cdnv1app
    links:
      - postgres
    command: mvn clean spring-boot:run
    depends_on:
      - postgres
    networks:
      - roadiniserver_proxynet

  apiv2:
    container_name: cdnapiv2
    image: cdnv2 
    working_dir: /cdnv2app
    volumes:
      - ./CDNservice/v2:/cdnv2app
    networks:
      - roadiniserver_proxynet

  recognition:
    container_name: imagerecognition
    image: imgrecog
    working_dir: /imageapp
    volumes:
      - ./ImageRecognition:/imageapp
    command: mvn clean spring-boot:run
    networks:
      - roadiniserver_proxynet

networks:
    roadiniserver_proxynet:
        external: true
