version: '3'

services:
  postgres:
    image: postgres:latest 
    container_name: db
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=dbCDN
    ports:
      - "8000:5432"

  api:
    build: ./CDNservice
    working_dir: /app
    volumes:
      - ./CDNserice:/app
    container_name: api
    links:
      - postgres
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - postgres
