version: '3'

services:
  postgres:
    image: postgres:latest 
    container_name: db
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=dbCDN
    ports:
      - "8000:5432"

  apiv1:
    build: ./CDNservice/v1
    working_dir: /app
    volumes:
      - ./CDNservice/v1:/app
    container_name: apiv1
    links:
      - postgres
    ports:
      - "8080:8080"
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - postgres

  apiv2:
    build: ./CDNservice/v2
    working_dir: /app
    volumes:
      - ./CDNservice/v2:/app
    container_name: apiv1
    ports:
      - "8082:8080"
    expose:
      - "8082"

  recognition:
    build: ./ImageRecognition
    working_dir: /imageApp
    volumes:
      - ./ImageRecognition:/imageApp
    container_name: imagerecognition
    ports:
      - "8081:8080"
    expose:
      - "8081"
    command: mvn clean spring-boot:run
